website/gov/urls.py
from django.urls import path, include

from . import views

app_name = 'gov'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # home
    path('desc', views.DescView.as_view(), name='desc'), # descending lease limit by 5
    path('asc', views.AscView.as_view(), name='asc'), # ascending lease limit by 5
    path('lease', views.LeaseDateView.as_view(), name='lease'), # get data between two dates
    path('add', views.DataCreate.as_view(), name='gov-add'), # add new data
    path('upload', views.upload_csv, name='upload_csv'), # upload csv
    path('count', views.CountView.as_view(), name='count'), # count number of mast by tenant
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gov.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/gov/models.py
from django.db import models
from django.urls import reverse
import datetime

class Data(models.Model):

    # Data Model
    property_name = models.CharField(default="",max_length=1000, blank=False)
    property_address1 = models.CharField(default="",max_length=1000, blank=True)
    property_address2 = models.CharField(default="",max_length=1000, blank=True)
    property_address3 = models.CharField(default="",max_length=1000, blank=True)
    property_address4 = models.CharField(default="",max_length=1000, blank=True)
    unit_name = models.CharField(default="",max_length=1000,blank=False)
    tenant_name = models.CharField(default="",max_length=1000,blank=False)
    lease_start_date = models.DateField(default=datetime.date.today,blank=True)
    lease_end_date = models.DateField(default=datetime.date.today,blank=True)
    lease_years = models.IntegerField(default=0,blank=True)
    current_rent = models.FloatField(default=0.0,blank=True)

    def __str__(self):
        return self.tenant_name

website/gov/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy, reverse
from .models import Data
import re, csv
from django.db.models import Sum
from django.db.models import Count
from datetime import datetime

class CountView(generic.ListView):
    template_name = 'gov/tenant.html'
    context_object_name = 'all_data'

    def get_queryset(self):

        # get count data by tenant
        tenant_list = Data.objects.all().values('tenant_name').annotate(total=Count('tenant_name'))

        # create object with tenants
        aggregated_tenants = {
            'Arqiva Services Ltd': [],
            'Cornerstone Telecommunications Infrastructure': [],
            'Everything Everywhere Ltd': [],
            'Everything Everywhere Ltd & Hutchinson 3G UK': [],
            'O2 (UK) Ltd': [],
            'Vodafone Ltd': []
        }

        # match tenant list with string and append data to object
        for tenant_and_masts in tenant_list:
            name = tenant_and_masts['tenant_name']
            if 'Arqiva' in name:
                aggregated_tenants['Arqiva Services Ltd'].append(tenant_and_masts)
            elif 'Cornerstone' in name:
                aggregated_tenants['Cornerstone Telecommunications Infrastructure'].append(tenant_and_masts)
            elif '&' in name:
                aggregated_tenants['Everything Everywhere Ltd & Hutchinson 3G UK'].append(tenant_and_masts)
            elif 'Everything' in name:
                aggregated_tenants['Everything Everywhere Ltd'].append(tenant_and_masts)
            elif 'O2' in name:
                aggregated_tenants['O2 (UK) Ltd'].append(tenant_and_masts)
            elif 'Vodafone' in name:
                aggregated_tenants['Vodafone Ltd'].append(tenant_and_masts)

        all = [];

        # combine tenates values and store in all
        for aggregated_tenant in aggregated_tenants:
            tenant_and_mast = {
                'tenant_name': aggregated_tenant,
                'total': 0
            }
            for tenant_and_masts in aggregated_tenants[aggregated_tenant]:
                tenant_and_mast['total'] += tenant_and_masts['total']
            all.append(tenant_and_mast)

        return [all, # all tenants with total value 
                Data.objects.aggregate(Sum('current_rent'))]; # query sum rent
  
class IndexView(generic.ListView):
    template_name = 'gov/index.html'
    context_object_name = 'all_data'
    def get_queryset(self):
        return [
            Data.objects.order_by("lease_years") , # query aAll data order by ascending
            Data.objects.aggregate(Sum('current_rent')) # query sum rent
        ]

class LeaseDateView(generic.ListView):
    # view returns data between 01-Jine-99 and 31-Aug-07 and total rent
    template_name = 'gov/lease_date.html'
    context_object_name = 'all_data'
    def get_queryset(self):       
        format = '%d-%b-%y' # data format
        start_date = datetime.strptime("01-Jun-99", format) # start date
        end_date = datetime.strptime("31-Aug-07", format) # end date
        return [Data.objects.filter(lease_start_date__range=(start_date, end_date)), # query data between
                Data.objects.aggregate(Sum('current_rent'))] # query sum rent

class DescView(generic.ListView):
    # view returns lease years in order of descending limited by 5 and total rent
    template_name = 'gov/top.html' 
    context_object_name = 'all_data'
    def get_queryset(self):
        return [Data.objects.order_by("-lease_years")[:5], # query lease descending limited 5
                Data.objects.aggregate(Sum('current_rent'))] # query sum rent

class AscView(generic.ListView):
    # view returns lease years in order of ascending limited by 5 and total rent
    template_name = 'gov/top.html'
    context_object_name = 'all_data'
    def get_queryset(self):
        return [Data.objects.order_by("lease_years")[:5], # query lease ascending limited 5
                Data.objects.aggregate(Sum('current_rent'))] # query sum rent

class DataCreate(CreateView):
    # view for creating a display form for adding new data
    model = Data
    fields = ['property_name','property_address1','property_address2','property_address3','property_address4',
              'unit_name','tenant_name','lease_start_date','lease_end_date','lease_years','current_rent']
    success_url = reverse_lazy('gov:index')

def upload_csv(request):
    data = {}

    if "GET" == request.method:
        return render(request, "gov/upload_csv.html", data)
    # if not GET, then proceed

    csv_file = request.FILES["csv_file"]

    # check file type
    if not csv_file.name.endswith('.csv'):
        return HttpResponseRedirect(reverse("gov:upload_csv"))

    # check file size
    if csv_file.multiple_chunks():
        return HttpResponseRedirect(reverse("gov:upload_csv"))
    

    file_data = csv_file.read().decode("utf-8")     

    lines = file_data.split("\r\n")

    reader = csv.reader(lines, skipinitialspace=True)

    # skip header
    next(reader)

    for row in reader:

        # ignore first row
        if len(row) > 1:

 
             # format dates
            format = '%d-%b-%y'
            start_date = datetime.strptime(row[7], format)
            end_date = datetime.strptime(row[8], format)


            # clean fields
            def clean(field):
                return field.strip()

            # store in Data object
            m = Data(
                property_name = clean(row[0]),
                property_address1 = clean(row[1]),
                property_address2 = clean(row[2]),
                property_address3 = clean(row[3]),
                property_address4 = clean(row[4]),
                unit_name = clean(row[5]),
                tenant_name = clean(row[6]),
                lease_start_date = start_date,
                lease_end_date = end_date,
                lease_years = row[9],
                current_rent = row[10]
            )

            m.save()
    
    # return to home page
    return HttpResponseRedirect(reverse("gov:index"))

    

website/gov/templates/gov/base.html
{% load humanize %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Test v2</title>

    <!-- Loads the path to your static files -->
    {% load static %}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Google Font - Pacifico -->
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'gov/style.css' %}" />
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fuild">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collage" data-target="#topNavBar">
                    <!-- When screen is small display nav icon -->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'gov:index' %}">Test</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'gov:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Lease
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'gov:desc' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Top 5
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'gov:lease' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Lease Date
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'gov:count' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Count Tenant
                        </a>
                    </li>
                </ul>


                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="">
                            <span aria-hidden="true"></span>&nbsp; Total Rent: £{{ all_data.1.current_rent__sum | intcomma }}
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'gov:gov-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Data
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'gov:upload_csv' %}">
                            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; File
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>

    {% block body %}
    {% endblock %}

</body>

</html>

website/gov/templates/gov/data_form.html
{% extends 'gov/base.html' %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'gov/form-template.html '%}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Sumbit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/gov/templates/gov/form-template.html
{% for field in form %}
<div class="form-group">
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

website/gov/templates/gov/index.html
{% extends 'gov/base.html' %}

{% block body %}

<center><h2>List Sorted By Lease Amount In Ascending Order</h2></center>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Property Name</th>
            <th>Property Address [1]</th>
            <th>Property Address [2]</th>
            <th>Property Address [3]</th>
            <th>Property Address [4]</th>
            <th>Unit Name</th>
            <th>Tenant Name</th>
            <th>Lease Start Date</th>
            <th>Lease End Date</th>
            <th>Lease Years</th>
            <th>Current Rent</th>
        </tr>
    </thead>
    <tbody>

        {% for data in all_data.0 %}
        <tr>
            <td>{{ data.property_name }}</td>
            <td>{{ data.property_address1 }}</td>
            <td>{{ data.property_address2 }}</td>
            <td>{{ data.property_address3 }}</td>
            <td>{{ data.property_address4 }}</td>
            <td>{{ data.unit_name }}</td>
            <td>{{ data.tenant_name }}</td>
            <td>{{ data.lease_start_date }}</td>
            <td>{{ data.lease_end_date }}</td>
            <td>{{ data.lease_years }}</td>
            <td>{{ data.current_rent }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

website/gov/templates/gov/lease_date.html
{% extends 'gov/base.html' %}

{% block body %}

<center><h2>Lease Start Date between 1 June 1999 and 31 Aug 2007</h2></center>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Property Name</th>
            <th>Property Address [1]</th>
            <th>Property Address [2]</th>
            <th>Property Address [3]</th>
            <th>Property Address [4]</th>
            <th>Unit Name</th>
            <th>Tenant Name</th>
            <th>Lease Start Date</th>
            <th>Lease End Date</th>
            <th>Lease Years</th>
            <th>Current Rent</th>
        </tr>
    </thead>
    <tbody>

        {% for data in all_data.0 %}
        <tr>
            <td>{{ data.property_name }}</td>
            <td>{{ data.property_address1 }}</td>
            <td>{{ data.property_address2 }}</td>
            <td>{{ data.property_address3 }}</td>
            <td>{{ data.property_address4 }}</td>
            <td>{{ data.unit_name }}</td>
            <td>{{ data.tenant_name }}</td>
            <td>{{ data.lease_start_date | date:"d/m/Y" }}</td>
            <td>{{ data.lease_end_date | date:"d/m/Y"}}</td>
            <td>{{ data.lease_years }}</td>
            <td>{{ data.current_rent }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

website/gov/templates/gov/tenant.html
{% extends 'gov/base.html' %}

{% block body %}



<table class="table table-hover">

    <thead>
        <tr>
            <th>Tenant Name</th>
            <th>Count of Masts </th>
        </tr>
    </thead>
    <tbody>

        {% for data in all_data.0 %}
        <tr>
            <td>{{ data.tenant_name }}</td>
            <td>{{ data.total }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

website/gov/templates/gov/top.html
{% extends 'gov/base.html' %}

{% block body %}


<center>
    <button type="button" class="btn btn-primary" onclick="location.href = '{% if request.path == '/asc' %}{% url 'gov:desc' %}{% else %}{% url 'gov:asc' %}{% endif %}';">
        Sort Lease Years by 
        {% if request.path == '/asc' %}
            Descending
        {% else %}
            Ascending
        {% endif %}

    </button>
</center>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Property Name</th>
            <th>Property Address [1]</th>
            <th>Property Address [2]</th>
            <th>Property Address [3]</th>
            <th>Property Address [4]</th>
            <th>Unit Name</th>
            <th>Tenant Name</th>
            <th>Lease Start Date</th>
            <th>Lease End Date</th>
            <th>Lease Years</th>
            <th>Current Rent</th>
        </tr>
    </thead>
    <tbody>

        {% for data in all_data.0 %}
        <tr>
            <td>{{ data.property_name }}</td>
            <td>{{ data.property_address1 }}</td>
            <td>{{ data.property_address2 }}</td>
            <td>{{ data.property_address3 }}</td>
            <td>{{ data.property_address4 }}</td>
            <td>{{ data.unit_name }}</td>
            <td>{{ data.tenant_name }}</td>
            <td>{{ data.lease_start_date }}</td>
            <td>{{ data.lease_end_date }}</td>
            <td>{{ data.lease_years }}</td>
            <td>{{ data.current_rent }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

website/gov/templates/gov/upload_csv.html
{% extends 'gov/base.html' %}

{% block body %}

    <form action="{% url "gov:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
            <div class="col-md-8">
                <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
            </div>
        </div>
    </form>

{% endblock %}